version: '3'
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./data-grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: compteur-info
    volumes:
      - ./data-influx:/var/lib/influxdb

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883

